// Database interface - matches Supabase schema exactly with snake_case
export interface VysnProductDB {
  id: number;
  vysn_name?: string;
  item_number_vysn?: string;
  short_description?: string;
  long_description?: string;
  weight_kg?: number;
  packaging_weight_kg?: number;
  gross_weight_kg?: number;
  installation_diameter?: number;
  cable_length_mm?: number;
  diameter_mm?: number;
  length_mm?: number;
  width_mm?: number;
  height_mm?: number;
  packaging_width_mm?: number;
  packaging_length_mm?: number;
  packaging_height_mm?: number;
  housing_color?: string;
  material?: string;
  gross_price?: number;
  katalog_q4_24?: boolean;
  category_1?: string;
  category_2?: string;
  group_name?: string;
  light_direction?: string;
  lumen?: number;
  driver_info?: string;
  beam_angle?: number;
  beam_angle_range?: string;
  lightsource?: string;
  luminosity_decrease?: string;
  steering?: string;
  led_chip_lifetime?: string;
  energy_class?: string;
  cct?: number;
  cri?: number;
  wattage?: number;
  led_type?: string;
  sdcm?: string;
  operating_mode?: string;
  lumen_per_watt?: number;
  cct_switch_value?: string;
  power_switch_value?: string;
  ingress_protection?: string;
  protection_class?: string;
  impact_resistance?: string;
  ugr?: number;
  installation?: string;
  base_socket?: string;
  number_of_sockets?: number;
  socket_information_retrofit?: string;
  replaceable_light_source?: boolean;
  coverable?: boolean;
  manual_link?: string;
  barcode_number?: string;
  hs_code?: string;
  packaging_units?: number;
  country_of_origin?: string;
  eprel_link?: string;
  eprel_picture_link?: string;
  product_picture_1?: string;
  product_picture_2?: string;
  product_picture_3?: string;
  product_picture_4?: string;
  product_picture_5?: string;
  product_picture_6?: string;
  product_picture_7?: string;
  product_picture_8?: string;
  availability?: boolean;
  created_at?: string;
  updated_at?: string;
}

// Client interface - converted to camelCase for use in UI components
export interface VysnProduct {
  id: number;
  vysnName: string;
  itemNumberVysn: string;
  shortDescription: string;
  longDescription: string;
  weightKg?: number;
  packagingWeightKg?: number;
  grossWeightKg?: number;
  installationDiameter?: number;
  cableLengthMm?: number;
  diameterMm?: number;
  lengthMm?: number;
  widthMm?: number;
  heightMm?: number;
  packagingWidthMm?: number;
  packagingLengthMm?: number;
  packagingHeightMm?: number;
  housingColor?: string;
  material?: string;
  grossPrice?: number;
  katalogQ424?: boolean;
  category1?: string;
  category2?: string;
  groupName?: string;
  lightDirection?: string;
  lumen?: number;
  driverInfo?: string;
  beamAngle?: number;
  beamAngleRange?: string;
  lightsource?: string;
  luminosityDecrease?: string;
  steering?: string;
  ledChipLifetime?: string;
  energyClass?: string;
  cct?: number;
  cri?: number;
  wattage?: number;
  ledType?: string;
  sdcm?: string;
  operatingMode?: string;
  lumenPerWatt?: number;
  cctSwitchValue?: string;
  powerSwitchValue?: string;
  ingressProtection?: string;
  protectionClass?: string;
  impactResistance?: string;
  ugr?: number;
  installation?: string;
  baseSocket?: string;
  numberOfSockets?: number;
  socketInformationRetrofit?: string;
  replaceableLightSource?: boolean;
  coverable?: boolean;
  manuallink?: string;
  barcodeNumber?: string;
  hsCode?: string;
  packagingUnits?: number;
  countryOfOrigin?: string;
  eprelLink?: string;
  eprelPictureLink?: string;
  product_picture_1?: string;
  product_picture_2?: string;
  product_picture_3?: string;
  product_picture_4?: string;
  product_picture_5?: string;
  product_picture_6?: string;
  product_picture_7?: string;
  product_picture_8?: string;
  availability?: boolean;
  createdAt?: string;
  updatedAt?: string;
}

// Utility function to convert database product to client product
export function convertDbToClientProduct(dbProduct: VysnProductDB): VysnProduct {
  return {
    id: dbProduct.id,
    vysnName: dbProduct.vysn_name || '',
    itemNumberVysn: dbProduct.item_number_vysn || '',
    shortDescription: dbProduct.short_description || '',
    longDescription: dbProduct.long_description || '',
    weightKg: dbProduct.weight_kg,
    packagingWeightKg: dbProduct.packaging_weight_kg,
    grossWeightKg: dbProduct.gross_weight_kg,
    installationDiameter: dbProduct.installation_diameter,
    cableLengthMm: dbProduct.cable_length_mm,
    diameterMm: dbProduct.diameter_mm,
    lengthMm: dbProduct.length_mm,
    widthMm: dbProduct.width_mm,
    heightMm: dbProduct.height_mm,
    packagingWidthMm: dbProduct.packaging_width_mm,
    packagingLengthMm: dbProduct.packaging_length_mm,
    packagingHeightMm: dbProduct.packaging_height_mm,
    housingColor: dbProduct.housing_color,
    material: dbProduct.material,
    grossPrice: dbProduct.gross_price,
    katalogQ424: dbProduct.katalog_q4_24,
    category1: dbProduct.category_1,
    category2: dbProduct.category_2,
    groupName: dbProduct.group_name,
    lightDirection: dbProduct.light_direction,
    lumen: dbProduct.lumen,
    driverInfo: dbProduct.driver_info,
    beamAngle: dbProduct.beam_angle,
    beamAngleRange: dbProduct.beam_angle_range,
    lightsource: dbProduct.lightsource,
    luminosityDecrease: dbProduct.luminosity_decrease,
    steering: dbProduct.steering,
    ledChipLifetime: dbProduct.led_chip_lifetime,
    energyClass: dbProduct.energy_class,
    cct: dbProduct.cct,
    cri: dbProduct.cri,
    wattage: dbProduct.wattage,
    ledType: dbProduct.led_type,
    sdcm: dbProduct.sdcm,
    operatingMode: dbProduct.operating_mode,
    lumenPerWatt: dbProduct.lumen_per_watt,
    cctSwitchValue: dbProduct.cct_switch_value,
    powerSwitchValue: dbProduct.power_switch_value,
    ingressProtection: dbProduct.ingress_protection,
    protectionClass: dbProduct.protection_class,
    impactResistance: dbProduct.impact_resistance,
    ugr: dbProduct.ugr,
    installation: dbProduct.installation,
    baseSocket: dbProduct.base_socket,
    numberOfSockets: dbProduct.number_of_sockets,
    socketInformationRetrofit: dbProduct.socket_information_retrofit,
    replaceableLightSource: dbProduct.replaceable_light_source,
    coverable: dbProduct.coverable,
    manuallink: dbProduct.manual_link,
    barcodeNumber: dbProduct.barcode_number,
    hsCode: dbProduct.hs_code,
    packagingUnits: dbProduct.packaging_units,
    countryOfOrigin: dbProduct.country_of_origin,
    eprelLink: dbProduct.eprel_link,
    eprelPictureLink: dbProduct.eprel_picture_link,
    product_picture_1: dbProduct.product_picture_1,
    product_picture_2: dbProduct.product_picture_2,
    product_picture_3: dbProduct.product_picture_3,
    product_picture_4: dbProduct.product_picture_4,
    product_picture_5: dbProduct.product_picture_5,
    product_picture_6: dbProduct.product_picture_6,
    product_picture_7: dbProduct.product_picture_7,
    product_picture_8: dbProduct.product_picture_8,
    availability: dbProduct.availability,
    createdAt: dbProduct.created_at,
    updatedAt: dbProduct.updated_at,
  };
}